In [1]:
# pandas : 자료구조 및 데이터 분석 처리를 위한 파이썬의 핵심 패키지
# import pandas as pd
# Series & DataFrame

In [2]:
# Series : index와 value 형태의 자료 구조 (cf. 리스트는 value만 있음)

In [3]:
# pandas 함수 불러오기
import pandas as pd
from pandas import Series, DataFrame

# Series 설정
a = Series([1, 3, 5, 7])
print(a)
print(a.values)
print(a.index)

# index 변경
a2 = pd.Series([1, 3, 5, 7], index=['a', 'b', 'c', 'd'])
print(a2)

0    1
1    3
2    5
3    7
dtype: int64
[1 3 5 7]
RangeIndex(start=0, stop=4, step=1)
a    1
b    3
c    5
d    7
dtype: int64

In [4]:
# DataFrame : 2차원 행렬구조

In [3]:
# 엑셀 파일을 pandas DataFrame 형태로 불러오기
import pandas as pd
df = pd.read_excel('Ex_GrapeData.xlsx')
df

    continent  brand  size  period  price
0           2      2  10.7   47.65  144.0
1           2      3  14.0   63.13  215.0
2           2      2   9.0   58.76  105.0
3           1      1   8.0   34.88   69.0
4           2      2  10.0   55.53  134.0
..        ...    ...   ...     ...    ...
58          1      1   5.0   16.66   21.5
59          2      1  21.0   43.00    NaN
60          2      2   5.0   12.00    NaN
61          2      3  13.0   20.00    NaN
62          2      3  31.0   19.00    NaN

[63 rows x 5 columns]